// api/_lib/detectors/spacer.js
//
// Detects parts generated by the third-party "Spacer" FeatureScript
// (source reviewed — see SPACER_AUTO_DETECTION_ROADMAP.md). We do NOT fork
// or modify that FeatureScript, so detection relies entirely on its
// legacy parameter signature — no PARTSHELF_GENERATOR_ID marker exists
// and none will be added.
//
// v1 scope:
//   • BLIND-end spacers get OD (externalDia), internal adder, and length
//     directly from parameter `expression` strings in
//     GET .../partstudios/.../features — no extra Onshape call needed.
//   • UP_TO_FACE length and ROUND spacers' true ID both require resolving
//     real geometry (the origin edge's radius, and evDistance against the
//     picked end face) that isn't in the plain parameter list. For these,
//     inspectPartStudioFeatures() attaches an `evalRequest` (a small
//     FeatureScript snippet + a { origin: [deterministicId], endFace?:
//     [deterministicId] } map lifted straight from the feature's own
//     parameters) that the caller (the detection endpoint) submits via
//     evalFeatureScript() — see
//     onshape-partstudio-features.js. applyEvalResult() then merges the
//     resolved numbers back in and upgrades status/confidence once a
//     match is fully known. If eval fails or its response can't be
//     parsed, the row falls back to 'needs_review' with a warning rather
//     than blocking.
//   • HEX / HEX375 spacers never had a real "ID" concept — the profile
//     size is a fixed wrench-size constant (0.5"/0.375" across flats)
//     plus internalAdd/2, not derived from the origin edge at all. We
//     report `acrossFlats` for these instead of `id`.

const REQUIRED_PARAM_IDS = ['spacerType', 'internalAdd', 'externalDia', 'endType', 'origin']

const HEX_ACROSS_FLATS_BASE_IN = {
  HEX:    0.5,
  HEX375: 0.375,
}

/** Cheap local prefilter over an already-parsed BOM row — avoids firing
 *  any Onshape request for rows that obviously aren't spacer candidates. */
export function candidateFilter(row) {
  if (!row.partName) return false
  const name = row.partName.toLowerCase()
  const partNumber = (row.partNumber || '').toLowerCase()
  if (!name.includes('spacer') && !partNumber.includes('spacer')) return false

  // COTS/standard-content parts are never something we auto-detect for
  // fabrication, regardless of name.
  if (row.raw?.isStandardContent) return false

  return true
}

/** Per the roadmap: a candidate whose source document differs from the
 *  imported assembly's own root document is treated as an
 *  outside/vendor spacer and excluded from auto-detection entirely. */
function isFromRootDocument(row, rootDocumentId) {
  return !!row.raw?.documentId && row.raw.documentId === rootDocumentId
}

/** Parses an Onshape parameter `expression` string like "0.375 in" into
 *  { value, unit }. Falls back gracefully if the format is unexpected —
 *  callers treat a null value as "couldn't resolve, needs review". */
function parseExpression(expr) {
  if (!expr || typeof expr !== 'string') return null
  const m = expr.trim().match(/^(-?[\d.]+)\s*([a-zA-Z]+)?$/)
  if (!m) return null
  const value = parseFloat(m[1])
  if (!Number.isFinite(value)) return null
  return { value, unit: m[2] || 'in' }
}

function paramByIdMap(feature) {
  const map = {}
  for (const p of feature.parameters || []) {
    if (p.parameterId) map[p.parameterId] = p
  }
  return map
}

/** True if a feature's parameter set matches the legacy Spacer signature. */
function matchesLegacySpacerSignature(feature) {
  if (feature.featureType !== 'myFeature') return false
  const params = paramByIdMap(feature)
  return REQUIRED_PARAM_IDS.every(id => id in params)
}

/**
 * Given the already-fetched feature list for ONE Part Studio, returns a
 * dimensions/confidence result for every feature in it that matches the
 * legacy spacer signature. Does not call Onshape again — the caller
 * (the detection endpoint) is responsible for fetching the feature list
 * once per unique source Part Studio and passing it in here.
 */

/**
 * Builds a { script, queries } payload for evalFeatureScript(), re-deriving
 * exactly the values the original Spacer FeatureScript computes internally
 * (originCirc.radius for ID; evDistance against the end face for
 * UP_TO_FACE length) — without forking that script. `queries` values are
 * the query strings lifted straight off this feature's own origin/endFace
 * parameters, so the geometry resolved is guaranteed to be the exact
 * entities this exact feature instance picked.
 *
 * IMPORTANT: the eval endpoint parses `script` as a single FeatureScript
 * EXPRESSION, not a full script file — confirmed via a live 400 response
 * (BTFeatureScriptEvalResponse-1859 with PARSE notices) rejecting both a
 * leading `FeatureScript 1120;` version pragma and an `import(...)`
 * statement, since neither is valid at the start of / within a bare
 * expression. No import is needed anyway: eval runs inside the target
 * Part Studio's own already-resolved environment, so `evCurveDefinition`,
 * `plane`, `evDistance`, and `inch` are already in scope. The script here
 * is just the anonymous function literal itself, no pragma/import/semicolon
 * wrapper.
 *
 * Returns null if nothing needs eval (BLIND + non-ROUND, fully known
 * already) or if the required query parameter data isn't present.
 */
function buildEvalRequest(spacerType, endType, originParam, endFaceParam) {
  const needsId     = spacerType === 'ROUND'
  const needsLength = endType === 'UP_TO_FACE'
  if (!needsId && !needsLength) return null

  // The eval endpoint's `queries` map wants each entity referenced by its
  // short `deterministicIds[0]` token (e.g. "JFB") — NOT the serialized
  // `queryString` blob (query=qCompressed(...);) and NOT the full query
  // object. Confirmed via live testing: a queryString-based request
  // consistently resolved to zero matches (CANNOT_RESOLVE_ENTITIES /
  // matchCount: 0) even against a query provably pointing at real,
  // present geometry, while the bare deterministicIds[0] token resolved
  // correctly on the first try.
  const originId = originParam?.queries?.[0]?.deterministicIds?.[0]
  if (!originId) return null

  const queries = { origin: [originId] }
  let canComputeLength = false

  if (needsLength) {
    const endFaceId = endFaceParam?.queries?.[0]?.deterministicIds?.[0]
    if (endFaceId) {
      queries.endFace = [endFaceId]
      canComputeLength = true
    }
  }

  const script = `function(context is Context, queries is map) returns map
{
    var originCirc = evCurveDefinition(context, { "edge" : queries.origin });
    var face = plane(originCirc.coordSystem);
    var result = {};
    result["radius"] = originCirc.radius / inch;
    ${canComputeLength ? `
    result["length"] = evDistance(context, {
        "side0" : queries.endFace,
        "side1" : face,
        "extendSide0" : true,
        "extendSide1" : true
    }).distance / inch;
    ` : ''}
    return result;
}`

  return { script, queries, needsId, needsLength: canComputeLength }
}

/**
 * Merges a resolved evalFeatureScript result back into a match's
 * dimensions, upgrading status/confidence to 'detected'/'high' once
 * everything required for this spacer's type is known. Never downgrades —
 * if eval only resolved part of what was missing (or failed entirely),
 * the match stays 'needs_review' with an explanatory warning instead of
 * silently pretending completeness.
 */
export function applyEvalResult(match, evalOutcome) {
  const { radius, length, error } = evalOutcome
  const warnings = [...match.warnings]
  const dims = { ...match.dimensions }

  if (error) {
    warnings.push(`FeatureScript eval failed: ${error} — confirm dimensions manually.`)
  } else {
    if (match.spacerType === 'ROUND' && typeof radius === 'number') {
      // Mirrors the FeatureScript: ID = 2*originCirc.radius + internalAdd
      const internalAdd = dims.internalAdd?.value ?? 0
      dims.id = { value: +(2 * radius + internalAdd).toFixed(4), unit: 'in' }
    }
    if (match.endType === 'UP_TO_FACE' && typeof length === 'number') {
      dims.length = { value: +length.toFixed(4), unit: 'in' }
    }
  }

  const hasOd     = !!dims.od
  const hasLength = !!dims.length
  const hasIdOrFlats = match.spacerType === 'ROUND' ? !!dims.id : !!dims.acrossFlats

  const complete = hasOd && hasLength && hasIdOrFlats
  return {
    ...match,
    dimensions: dims,
    status:     complete ? 'detected' : 'needs_review',
    confidence: complete ? 'high' : match.confidence,
    warnings,
  }
}

export function inspectPartStudioFeatures(featureListResponse) {
  const features = featureListResponse?.features || []
  const matches = []

  for (const feature of features) {
    if (!matchesLegacySpacerSignature(feature)) continue
    const params = paramByIdMap(feature)

    const spacerType = params.spacerType?.value || null   // 'ROUND' | 'HEX' | 'HEX375'
    const endType     = params.endType?.value || null      // 'BLIND' | 'UP_TO_FACE'
    const internalAdd = parseExpression(params.internalAdd?.expression)
    const externalDia = parseExpression(params.externalDia?.expression)
    const lengthParsed = parseExpression(params.myLength?.expression)

    const warnings = []
    let confidence = 'medium'
    let status = 'needs_review'
    let length = null

    if (endType === 'BLIND') {
      // Length's expression is trustworthy only for BLIND — for
      // UP_TO_FACE it's a stale/leftover value from the parameter's last
      // BLIND state, not the computed distance (confirmed against a real
      // features response — the expression sits at a default like "1 in"
      // regardless of the actual up-to-face distance).
      length = lengthParsed
      if (spacerType && internalAdd && externalDia && length) {
        confidence = 'high'
        status = 'detected'
      } else {
        warnings.push('Could not parse one or more BLIND spacer parameters.')
      }
    } else if (endType === 'UP_TO_FACE') {
      // Length isn't known yet — buildEvalRequest below will ask Onshape
      // to resolve it via evDistance. Status stays needs_review until the
      // eval result comes back (applyEvalResult may upgrade it).
      warnings.push('Up-to-face length requires FeatureScript evaluation — resolving via evalFeatureScript.')
    } else {
      warnings.push(`Unrecognized endType "${endType}".`)
    }

    let od = externalDia ? { value: externalDia.value, unit: externalDia.unit } : null
    let id = null
    let acrossFlats = null

    if (spacerType === 'ROUND') {
      // ID isn't known yet — buildEvalRequest below will ask Onshape to
      // resolve originCirc.radius. Status stays needs_review until the
      // eval result comes back (applyEvalResult may upgrade it).
      warnings.push('Round spacer ID requires FeatureScript evaluation — resolving via evalFeatureScript.')
    } else if (spacerType === 'HEX' || spacerType === 'HEX375') {
      const base = HEX_ACROSS_FLATS_BASE_IN[spacerType]
      if (base != null && internalAdd) {
        // Mirrors the FeatureScript: hexSize = base*1.1548in + internalAdd/2
        // internalAdd is assumed to already be in inches here (fine for v1
        // since the category's units are inches); a mixed-unit document
        // would need real unit conversion, flagged as a warning instead.
        if (internalAdd.unit && internalAdd.unit !== 'in') {
          warnings.push(`internalAdd unit "${internalAdd.unit}" is not inches — acrossFlats not computed.`)
        } else {
          acrossFlats = { value: +(base * 1.1548 + internalAdd.value / 2).toFixed(4), unit: 'in' }
        }
      }
    } else {
      warnings.push(`Unrecognized spacerType "${spacerType}".`)
      status = 'needs_review'
    }

    const evalRequest = buildEvalRequest(spacerType, endType, params.origin, params.endFace)
    if (endType === 'UP_TO_FACE' && evalRequest && !evalRequest.needsLength) {
      // UP_TO_FACE but endFace query data wasn't present on the parameter
      // (shouldn't normally happen, but fail safe) — flag it rather than
      // silently eval'ing only the radius and pretending length is known.
      warnings.push('Could not resolve the end-face query for this feature — length still requires manual confirmation.')
    }

    matches.push({
      featureId: feature.featureId,
      spacerType,
      endType,
      confidence,
      status,
      dimensions: {
        od,
        id,                 // null until eval resolves it (ROUND only)
        acrossFlats,        // HEX/HEX375 only
        length,             // populated for BLIND directly; null for UP_TO_FACE until eval
        internalAdd,
      },
      warnings,
      evalRequest,          // { script, queries } | null — consumed by the detection endpoint
    })
  }

  return matches
}

export const spacerDetector = {
  kind: 'spacer',
  generatorId: null,   // no PARTSHELF_GENERATOR_ID — legacy signature only, by design
  dataSource: 'features',   // tells the detection endpoint to use the features/evalFeatureScript path
  candidateFilter,
  isFromRootDocument,
  inspectPartStudioFeatures,
  applyEvalResult,
}
