// api/_lib/detectors/spacer.js
//
// Detects parts generated by the third-party "Spacer" FeatureScript
// (source reviewed — see SPACER_AUTO_DETECTION_ROADMAP.md). We do NOT fork
// or modify that FeatureScript, so detection relies entirely on its
// legacy parameter signature — no PARTSHELF_GENERATOR_ID marker exists
// and none will be added.
//
// v1 scope (by design):
//   • Only BLIND-end spacers reach status 'detected' — OD (externalDia),
//     internal adder, and length are all directly readable as parameter
//     `expression` strings from GET .../partstudios/.../features, no
//     extra Onshape call needed.
//   • UP_TO_FACE spacers, and ROUND spacers' true ID (which requires
//     resolving the picked origin edge's radius via evalFeatureScript),
//     are NOT computed in v1 — evalFeatureScript is intentionally
//     deferred. These land as 'needs_review' with whatever we DO know
//     (OD, spacer type, internal adder) so a human can fill in the rest
//     in the confirmation overlay.
//   • HEX / HEX375 spacers never had a real "ID" concept — the profile
//     size is a fixed wrench-size constant (0.5"/0.375" across flats)
//     plus internalAdd/2, not derived from the origin edge at all. We
//     report `acrossFlats` for these instead of `id`.

const REQUIRED_PARAM_IDS = ['spacerType', 'internalAdd', 'externalDia', 'endType', 'origin']

const HEX_ACROSS_FLATS_BASE_IN = {
  HEX:    0.5,
  HEX375: 0.375,
}

/** Cheap local prefilter over an already-parsed BOM row — avoids firing
 *  any Onshape request for rows that obviously aren't spacer candidates. */
export function candidateFilter(row) {
  if (!row.partName) return false
  const name = row.partName.toLowerCase()
  const partNumber = (row.partNumber || '').toLowerCase()
  if (!name.includes('spacer') && !partNumber.includes('spacer')) return false

  // COTS/standard-content parts are never something we auto-detect for
  // fabrication, regardless of name.
  if (row.raw?.isStandardContent) return false

  return true
}

/** Per the roadmap: a candidate whose source document differs from the
 *  imported assembly's own root document is treated as an
 *  outside/vendor spacer and excluded from auto-detection entirely. */
function isFromRootDocument(row, rootDocumentId) {
  return !!row.raw?.documentId && row.raw.documentId === rootDocumentId
}

/** Parses an Onshape parameter `expression` string like "0.375 in" into
 *  { value, unit }. Falls back gracefully if the format is unexpected —
 *  callers treat a null value as "couldn't resolve, needs review". */
function parseExpression(expr) {
  if (!expr || typeof expr !== 'string') return null
  const m = expr.trim().match(/^(-?[\d.]+)\s*([a-zA-Z]+)?$/)
  if (!m) return null
  const value = parseFloat(m[1])
  if (!Number.isFinite(value)) return null
  return { value, unit: m[2] || 'in' }
}

function paramByIdMap(feature) {
  const map = {}
  for (const p of feature.parameters || []) {
    if (p.parameterId) map[p.parameterId] = p
  }
  return map
}

/** True if a feature's parameter set matches the legacy Spacer signature. */
function matchesLegacySpacerSignature(feature) {
  if (feature.featureType !== 'myFeature') return false
  const params = paramByIdMap(feature)
  return REQUIRED_PARAM_IDS.every(id => id in params)
}

/**
 * Given the already-fetched feature list for ONE Part Studio, returns a
 * dimensions/confidence result for every feature in it that matches the
 * legacy spacer signature. Does not call Onshape again — the caller
 * (the detection endpoint) is responsible for fetching the feature list
 * once per unique source Part Studio and passing it in here.
 */
export function inspectPartStudioFeatures(featureListResponse) {
  const features = featureListResponse?.features || []
  const matches = []

  for (const feature of features) {
    if (!matchesLegacySpacerSignature(feature)) continue
    const params = paramByIdMap(feature)

    const spacerType = params.spacerType?.value || null   // 'ROUND' | 'HEX' | 'HEX375'
    const endType     = params.endType?.value || null      // 'BLIND' | 'UP_TO_FACE'
    const internalAdd = parseExpression(params.internalAdd?.expression)
    const externalDia = parseExpression(params.externalDia?.expression)
    const lengthParsed = parseExpression(params.myLength?.expression)

    const warnings = []
    let confidence = 'medium'
    let status = 'needs_review'
    let length = null

    if (endType === 'BLIND') {
      // Length's expression is trustworthy only for BLIND — for
      // UP_TO_FACE it's a stale/leftover value from the parameter's last
      // BLIND state, not the computed distance (confirmed against a real
      // features response — the expression sits at a default like "1 in"
      // regardless of the actual up-to-face distance).
      length = lengthParsed
      if (spacerType && internalAdd && externalDia && length) {
        confidence = 'high'
        status = 'detected'
      } else {
        warnings.push('Could not parse one or more BLIND spacer parameters.')
      }
    } else if (endType === 'UP_TO_FACE') {
      warnings.push('Up-to-face length requires evalFeatureScript, which v1 does not call — confirm length manually.')
    } else {
      warnings.push(`Unrecognized endType "${endType}".`)
    }

    let od = externalDia ? { value: externalDia.value, unit: externalDia.unit } : null
    let id = null
    let acrossFlats = null

    if (spacerType === 'ROUND') {
      warnings.push('Round spacer ID requires evalFeatureScript (origin edge radius), which v1 does not call — confirm ID manually.')
    } else if (spacerType === 'HEX' || spacerType === 'HEX375') {
      const base = HEX_ACROSS_FLATS_BASE_IN[spacerType]
      if (base != null && internalAdd) {
        // Mirrors the FeatureScript: hexSize = base*1.1548in + internalAdd/2
        // internalAdd is assumed to already be in inches here (fine for v1
        // since the category's units are inches); a mixed-unit document
        // would need real unit conversion, flagged as a warning instead.
        if (internalAdd.unit && internalAdd.unit !== 'in') {
          warnings.push(`internalAdd unit "${internalAdd.unit}" is not inches — acrossFlats not computed.`)
        } else {
          acrossFlats = { value: +(base * 1.1548 + internalAdd.value / 2).toFixed(4), unit: 'in' }
        }
      }
    } else {
      warnings.push(`Unrecognized spacerType "${spacerType}".`)
      status = 'needs_review'
    }

    matches.push({
      featureId: feature.featureId,
      spacerType,
      endType,
      confidence,
      status,
      dimensions: {
        od,
        id,                 // always null in v1 (ROUND) — needs eval
        acrossFlats,        // HEX/HEX375 only
        length,             // only populated for BLIND
        internalAdd,
      },
      warnings,
    })
  }

  return matches
}

export const spacerDetector = {
  kind: 'spacer',
  generatorId: null,   // no PARTSHELF_GENERATOR_ID — legacy signature only, by design
  candidateFilter,
  isFromRootDocument,
  inspectPartStudioFeatures,
}
